#!/usr/bin/env python3
"""PostToolUse hook (Write|Edit) - mechanical checks for the rules prose alone does not enforce.

Each check mirrors an invariant that is already written down in CLAUDE.md, README.md or
CONTRIBUTING.md, and fires at the moment a file that could break it is written:

  1. A credential-shaped string, or a non-placeholder e-mail address in data files. Nothing real
     belongs in this repository: no secret, no real person, no real books.
  2. A hosted analytics / error-tracking / telemetry service in shipping code. README.md promises
     there is none, and the Content-Security-Policy allows no such origin.
  3. Schema discipline: a schema change goes in BOTH db/schema_pg.sql and a new numbered
     migration, an applied migration is never edited, and every table carries row-level security.
  4. Test discipline: fixtures are synthetic and generated, and a test is never weakened or
     excluded to make a gate green.

Informational only - never blocks, always exits 0. Fail-soft everywhere.
"""
import json
import os
import re
import sys

SHIPPING_ROOTS = ("server/", "web/src/", "web/index.html", "core/", "config/", "db/", "models/",
                  "scripts/")
DATA_ROOTS = ("tests/", "config/", "docs/", "scripts/")

SECRET_RX = re.compile(
    r"AIza[0-9A-Za-z_\-]{30,}"                 # Google API key
    r"|\bsk-[A-Za-z0-9_\-]{20,}"               # OpenAI-style key
    r"|GOCSPX-[A-Za-z0-9_\-]{20,}"             # Google OAuth client secret
    r"|\d{6,}-[a-z0-9]{20,}\.apps\.googleusercontent\.com"
    r"|\bgh[pousr]_[A-Za-z0-9]{30,}"           # GitHub token
    r"|\bAKIA[0-9A-Z]{16}\b"                   # AWS access key id
    r"|-----BEGIN [A-Z ]*PRIVATE KEY-----"
    r"|postgres(?:ql)?://[^:/\s]+:(?!CHANGE_ME|postgres@|password@|\.\.\.)[^@\s]{6,}@")
EMAIL_RX = re.compile(r"[A-Za-z0-9._%+\-]+@([A-Za-z0-9\-]+\.)+[A-Za-z]{2,}")
PLACEHOLDER_EMAIL_RX = re.compile(r"@(example\.(com|org|net)|[a-z0-9\-]+\.(test|invalid|example)"
                                  r"|localhost|anthropic\.com)$", re.I)
TELEMETRY_RX = re.compile(
    r"sentry\.io|@sentry/|sentry_sdk|posthog|plausible\.io|google-analytics\.com|googletagmanager"
    r"|\bgtag\(|segment\.(com|io)|mixpanel|amplitude\.com|datadoghq|newrelic|bugsnag|logrocket"
    r"|hotjar|fullstory", re.I)
WEAKEN_RX = re.compile(r"pytest\.mark\.(skip|xfail)|pytest\.skip\(|unittest\.skip")


def real_emails(text):
    return sorted({m.group(0) for m in EMAIL_RX.finditer(text)
                   if not PLACEHOLDER_EMAIL_RX.search(m.group(0))})


def checks(rel, text):
    hits = []
    if SECRET_RX.search(text):
        hits.append("something shaped like a real credential - secrets live only in the "
                    "gitignored .env; use an obvious placeholder here")
    if rel.startswith(DATA_ROOTS):
        emails = real_emails(text)
        if emails:
            hits.append("a non-placeholder e-mail address (%s) - use @example.com; no real "
                        "person or business belongs in this repository" % emails[0])
    if rel.startswith(SHIPPING_ROOTS) and TELEMETRY_RX.search(text):
        hits.append("a hosted analytics/error-tracking reference - README.md promises no "
                    "telemetry and the CSP allows no such origin")
    if rel.startswith("db/migrations/") and rel.endswith(".sql"):
        hits.append("a migration - if this file was already applied anywhere, do not edit it; "
                    "add the next number instead, and mirror the change in db/schema_pg.sql")
    if rel == "db/schema_pg.sql":
        hits.append("the baseline schema - existing databases also need a new numbered file in "
                    "db/migrations/ carrying the same change")
    if rel.startswith("db/") and rel.endswith(".sql") and re.search(r"create\s+table", text, re.I) \
            and not re.search(r"enable\s+row\s+level\s+security", text, re.I):
        hits.append("CREATE TABLE with no ENABLE ROW LEVEL SECURITY in the same file - every "
                    "table needs a policy with USING and WITH CHECK on user_id = auth.uid() "
                    "(tests/test_rls_enforcement.py)")
    if rel.startswith("tests/fixtures/") and not rel.endswith("README.md"):
        hits.append("a fixture - fixtures are synthetic and generated by "
                    "scripts/gen_fixtures.py; read tests/fixtures/README.md, never hand-place "
                    "a real document or figure")
    if rel == "pytest.ini" or (rel.startswith("tests/") and WEAKEN_RX.search(text)):
        hits.append("a test exclusion or skip - when a test catches a miss, fix the engine, "
                    "not the test; never weaken a test to make a gate green (CLAUDE.md)")
    return hits


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return
    path = (data.get("tool_input") or {}).get("file_path") or ""
    if not path or not os.path.exists(path):
        return

    root = os.environ.get("CLAUDE_PROJECT_DIR", "")
    try:
        rel = os.path.relpath(path, root).replace("\\", "/") if root else path
    except Exception:
        rel = path
    # The guardrail definitions legitimately contain the patterns they look for.
    if rel.startswith(".claude/hooks/"):
        return

    try:
        with open(path, encoding="utf-8", errors="ignore") as fh:
            text = fh.read()
    except Exception:
        return

    hits = checks(rel, text)
    if hits:
        print("[guardrail] %s: %s" % (rel, "; and ".join(hits)))


if __name__ == "__main__":
    try:
        main()
    except Exception:
        pass
    sys.exit(0)
